### ISSUE TITLE
include/imports

### ISSUE THREAD

**Issue by hugosenari** [eno-lang/eno#14]
Hi, this project is nice, please keep improving it.

Any plan for adding include or imports?

I known is a huge feature request dressed as two words.

Thank you.

**Comment by simonrepp** [comment]
Hey, thanks a lot for the feedback, appreciate it!

"Huge feature request dressed as two words" is a great way to put it haha :) - I did in fact think about such a possibility when eno was still a bit younger! I did abandon that train of thought mostly for this consideration: If eno were to specify an "include file" mechanism, that would make the assumption that eno files would always be in a file context, i.e. usecases like uploading an eno file to a website, or editing eno in a textfield on a website, or any number of scenarios where the eno source is maybe binary embedded in another file, would suddenly become brittle and call for special case handling of includes in a context where there is nothing to include. On top of that, closely related, every eno parser suddenly would need to be aware of the filesystem in some way, e.g. the javascript eno parser would need native filesystem routines (which of course don't exist in the browser like that), so there would be the need for a split package or something, one for (e.g.) a node environment, one for the browser, etc., same thing in other languages. I feel all of this would introduce so much complexity that it really takes eno away from what I intended it to be, something predictable, simple and easy to reason about. :)

More generally speaking, at this point I intend to add to the spec only whatever is necessary to wrap up what's already there - i.e. to resolve ambiguities, specify whatever isn't clearly specified yet, etc. On top of that there's one thing I'm actually pondering to *remove* again (deep copies), given that it allows some super far-fetched edge cases which to date not a single eno parser correctly handles (because it's so weirdly complex) - not that it is realistic at all that anyone will produce these exotic edge cases, but even the fact that something in eno is so complex to implement gives me the feeling I shouldn't have put it in there in the first place ...

Ok I digressed a bit here haha, hope my reply answered your question!

**Comment by hugosenari** [comment]
Thank you,

I'm seeking for data exchange formats and configuration DSL, most recent formats solves readability (YAML, TOML, Markdown) are good for data exchange, others modularity/reuse (CUE, Dhall, Jsonnet) are good for configurations dsl.

Eno has readability and reuse (`copies` and `deep copies`), import/include could improve modularity and makes it good for configuration DSL.

But if you plan remove deep copies there is no reason to add includes/imports.

"Perfection is achieved when there is nothing left to take away." (I'm not sure about who is original author).

Portability is one of reasons why liked Eno, and why I don't like Cue, Dhall, Jsonnet, etc. Loosing portability would be a great drawback as data exchange.

Random fact CSS has import since version 1 (1996) and JavaScript only in version 6 (2016), but CSS only gain var feature in 2015 :shrug:. CSS is nearly good as Eno, has copies (in its own way), with worse readability, but what the major problem I have with it is ubiquity, there is no CSS parser for any lang like YAML/JSON/TOML, maybe because of import complexity.

You answered my question.
Thank you again, I will close this.

**Comment by simonrepp** [comment]
Thanks for sharing your thoughts - I'll take that into account when further considering deep copies' fate!

Btw. YAML has reuse too (afaik), it's a complex beast with a daunting spec, but for that it at least offers a lot. :)
