### ISSUE TITLE
.NET (Core) support

### ISSUE THREAD

**Issue by DoCode** [eno-lang/eno#2]
Is anything in the pipe for this language?

**Comment by simonrepp** [comment]
You've hereby successfully put in on the radar, thanks! :) I have a crazy long todo list for the whole eno ecosystem in general, so realistically speaking I don't think I personally will get to it soon. If you are yourself potentially interested to work on a .NET implementation that's another story, let me know if that's the case because then I will provide you with some further ideas and possibilities for the process here! :)

**Comment by simonrepp** [comment]
I'm closing this for now, feel free to reopen if you want to pursue a .NET implementation and need support. Thanks again for your interest! :+1:
