### ISSUE TITLE
Line continuation w/o separator?

### ISSUE THREAD

**Issue by uasi** [eno-lang/eno#3]
Currently the line continuation operator automatically inserts a space character after it. This behavior is not ideal for non-Latin languages that don't usually use spaces between words, such as CJK (Chinese, Japanese, and Korean).

**Comment by simonrepp** [comment]
Fantastic you bring this up, this is exactly the sort of cultural bias mistake on my part I'd like to get fixed in the next/final spec. There were actually drafts for this exact feature which did not make it in the end, but given this insight they absolutely need to be reconsidered! I'll need some time to draw this up again and formalize it as an RFC thing, I'll get back to it! Thanks so much for pointing this out!

**Comment by simonrepp** [comment]
Hey @uasi,

I've given this a lot of time to really and deeply consider many options, and I can now finally and gladly present you the result. :) I'm very happy you made me rethink continuations because it triggered a deeper thought process on what fields are and how the continuation concept emerged and how to deal with adding complexity (in this case line continuation w/o separator) when I really want to make the language less complex, and I think it resulted in a very balanced and precise and not dramatically breaking change to the language. But ... I'll let the audience be the judge. ;)

Here's the RFC: 
https://github.com/eno-lang/eno/blob/master/rfcs-final-spec/restrict-fields-to-a-single-line.md

Thanks again!

**Comment by simonrepp** [comment]
I think we're done here, closing :)

**Comment by uasi** [comment]
Thanks @simonrepp , it's really well thought out 👍

**Comment by simonrepp** [comment]
Happy to hear!
