### ISSUE TITLE
re. rfc hybrid fieldsets: fieldset should always contain a list of entries

### ISSUE THREAD

**Issue by Nzen** [eno-lang/eno#6]
In light of the rfc for hybrid fieldsets (ie that aggregate the repeated entry values into a list), I recommend that fieldset entries always accommodate a list.

Which is to say, that we change the honored syntax for the lines following a fieldset assignment to include list entries (in addition to the current allowance for continuations). Semantically, libraries would aggregate these list entries as the value of that fieldset.
```
> current rfc
span :
 id = banana
 style = color: "#333";
 style = width: 33px;
 value = title of your document
 onclick = "alert( %s )"
 onclick = 'You pressed the span!'
```
```
> fieldset allows list
span:
 id = banana
 style =
  - color: "#333";
  - style: width: 33px;
 value = title of your document
 onclick = "alert( %s )"
   - 'You pressed the span!'
```
Duplicating the key introduces unnecessary noise to accomplish the same effect: introduce a list of values into a fieldset.

As to the core question of the rfc itself, I endorse it. Given that approving another rfc will change the newline continuation to an empty continuation, allowing multiple entries for the same fieldset simplifies adding separate lines (ex postal address or haiku) without post processing the value (ex replacing \n).

(Consider replacing the _dialog_ example in the rfc. Grouping all of Alice's lines together doesn't make much sense if we're looking at the conversation after an eno library has parsed the document. Unless those are interchangable npc responses to a repeated situation.)

**Comment by simonrepp** [comment]
Hey thanks for the feedback again!

I think I need to improve the RFC's clarity as far as the motivation for the hybrid fieldset is concerned. There is on the one hand the currently supported behavior (and thereby following types of usecases):

```eno
config:
level = verbose
max = 13
```
... this might on the API side be explicitly queried this way ... (showing JavaScript here for demonstration)
```js
const level = document.fieldset('config').string('level');
const max = document.fieldset('config').integer('max');
// ...
```

Then there's the cases where we read in unknown keys:

```eno
translations:
one = uno
two = dos
```
... queried something like this currently ...
```js
for(let translation of document.fieldset('translations').entries()) {
  const key = translation.name;
  const value = translation.string();
  // ...
}
```

And then there's the currently unsupported scenario which is the motivation for the RFC:

```eno
dialogue_lines:
Alice = Hi Bob.
Bob = Hey Alice!
Alice = What's up?
Bob = Not much!
```
... and this is what I intend this for ...
```js
for(let line of document.fieldset('dialogue_lines').entries()) {
  const actor = line.name;
  const text = line.string();
  // ... e.g. print the line
}
```

And then there's another thing one could do with this last eno document:
```js
const aliceLines = document.fieldset('dialogue_lines').strings('Alice');  // note: hypothetical API
// ...
```
... which does also make sense if I e.g. just want to analyze how many lines Alice has.

And with that background put in place (thanks for the patience ;)) I'll try to get to my point now:

```eno
span :
 id = banana
 style = color: "#333";
 style = width: 33px;
```
... is different from the `dialogue_lines` and `init_procedure` examples provided in the RFC in that there is no ordered interplay of keys represented here. It's true that the RFC also makes this usecase possible, but only as a (as you correctly point out, somewhat noisy) byproduct.

So to me this feels like (and with my attempted clarification about the original RFC's intent given I hope it makes sense) another, new RFC on a different aspect of fieldsets! Please let me know if any or all of this makes no sense for some reason! In any case I'll add another comment regarding your proposed changes later, this post is already a little long. :)

**Comment by simonrepp** [comment]
Ok now as to the proposed syntax changes:
Ideally all the final spec RFCs should only make eno simpler (especially and primarily when looking at it from a non-technical user perspective). Presently only the RFC for associated comments and the hybrid fieldset RFC violate that rule by introducing new stuff. With the first of the two I have no gripes because it is (I'd venture to say) purely opt-in for advanced usecases and practically non-existant from the perspective of an entry level user. With the hybrid fieldset RFC in its current state I'm just **barely** convinced of adopting it, because although from a user perspective the change is not very visible, there's already plenty of implications for user facing behavior, copying behavior, API design, for writing actual applications for eno, and so on.

Now if I were to go through with allowing lists in fieldset entries that would mean a whole avalanche of implications (if you're curious I can write down a rough list but to be honest I'd rather spend the time working on the ecosystem ;)), and in that light I hope it's understandable why I don't want to introduce such a large extension to the AST/API/syntax/etc.

Still it was very helpful you posted this because (as I tried to outline in the previous post) I think I failed to really communicate what the hybrid fieldset RFC is about at its core and I think I'll try to make some adaptions to that end in the document. :+1:

**Comment by Nzen** [comment]
Ah, so the idea of 'hybrid fieldset' is to just make fieldsets a _list_ of paired elements, rather than a _map_ of unique names to values. I published this issue thread as a reaction to the example given in the con section that represents the fieldset.
```
> contemporary rfc example
{ alice : [ line1, line3 ], bob : [ line2, line4 ] }

> implied in this thread
{[ {alice : line1}, {bob : line2}, {alice : line3}, {bob : line4} ]}
```
Sure, that's fine.
